# Generated by Django 5.2.8 on 2025-11-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalsyst', '0002_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='proforma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='approvalsyst.proforma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
