# Generated by Django 5.2.8 on 2025-11-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalsyst', '0003_purchaseorder_items_purchaseorder_proforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvalsyst.proforma'),
        ),
    ]
