# Generated by Django 5.2.8 on 2025-11-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalsyst', '0004_alter_purchaserequest_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approvalsyst.proforma'),
        ),
    ]
